# Generated by Django 4.0.6 on 2022-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_critics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='year',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
