# Generated by Django 4.0.6 on 2022-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_critics', '0002_series_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-title', 'year'], 'verbose_name': 'serie', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
