# Generated by Django 4.0.6 on 2022-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_critics', '0003_alter_series_options_alter_series_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
