# Generated by Django 4.0.6 on 2022-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nom')),
                ('role', models.CharField(choices=[('Actor', 'Actor'), ('Director', 'Director'), ('Musician', 'Musican'), ('Producer', 'Producer'), ('Writer', 'Writer')], max_length=32, verbose_name='Métier')),
                ('nationality', models.CharField(max_length=64, verbose_name='Nationalité')),
                ('birthdate', models.DateField(null=True, verbose_name='Date de Naissance')),
                ('birthplace', models.CharField(max_length=64, null=True, verbose_name='Lieu de naissance')),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='Photo')),
                ('like', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=2048)),
            ],
            options={
                'verbose_name': 'Personnalité',
                'ordering': ['last_name'],
            },
        ),
    ]
