# Generated by Django 4.0.6 on 2022-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name'], 'verbose_name': 'Person'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthplace',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
