# Generated by Django 4.0.6 on 2022-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_alter_contact_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
