# Generated by Django 4.0.6 on 2022-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_critics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescritics',
            name='author',
        ),
    ]
