# Generated by Django 4.0.6 on 2022-08-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_critics', '0003_gamescritics_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescritics',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
